### ISSUE TITLE
Applying CoType to Freebase

### ISSUE THREAD

**Issue by Henderake** [shanzhenren/CoType#1]
I found your work very interesting and I'd like to apply it to extract Freebase relations.
Could you give some hints on the code I should modified so that CoType can extract Freebase relations?

Thanks!

**Comment by shanzhenren** [comment]
Hi @Henderake. Yes you can! This is the right timing for us to say yes since we just push the [data pipeline code](https://github.com/shanzhenren/StructMineDataPipeline) out. The readme in data pipeline is still a bit messy. If you are on a tight deadline, it may give you some basic ideas and please shoot me and @ellenmellon questions. In principle, you can modify the type mapping files and change them to freebase types you want (we are already using freebase for distant supervision, so for you, this step is just to identify the target subset you are focusing on). Then you should be able to generate JSON input files for CoType systems, just like those we release here for download. 

- Xiang

**Comment by Henderake** [comment]
I'll tried out the pipeline code. Thank you!
